### ISSUE TITLE
A way to make all this smoother

### ISSUE THREAD

**Issue by Electorch** [SitronX/UnityTimeRewinder#3]
I switched FixedUpdate to Update as well as +=unscaledDeltaTime and set Time.timeScale = 0 when rewinding and back to 1 after because my falling objects were still falling while rewinding.

**Comment by SitronX** [comment]
Could you please more describe the issue? Rewinding should be smooth and i dont know what is the issue from what you described, could you provide video or something showing what it is doing? 

First:
FixedUpdate is there so rewinding by seconds is consistent. FixedUpdate runs consistently and is defaulty set to 50 times per second. Using Update breaks this consistency, because the FPS is varying throughout the game and Circular buffer is then storing values that may greatly vary in time. Update will not work with this, or will work but all weird stuff is gonna happen. 
<b>Stick with FixedUpdate</b>

But maybe you have fixed timestep value set to too high number and thus it saves the snapshots much less often than usual? That might be why it appears choppy or something. This is the default settings where state of the rewinded object is written 50 times per second into the circular buffer. 
![fixedUpdate](https://user-images.githubusercontent.com/68167377/220659090-0d1b2440-a390-413c-bf33-83d078306aa8.jpg)

**Comment by Electorch** [comment]
The main reason I changed everything from FixedUpdate to Update is just to add Time.timeScale = 0 to stop the objects falling while rewinding. Since FixedUpdate is scaled and not Update, unless you timeScale everything..

Since I'm making objects fall and I want to record their position, rotation and all velocity stuff so when I rewind it falls exactly the same since everything is just calculations. Before changing from FixedUpdate to Update, "it seems the objects were rewinding at a fixed step time, like it was missing in-between frames" now I get the same exact motion after rewinding-

-but only after the first time, the more times I rewind the more I'm missing until it just stop rewinding like it recorded only it's last position before hitting the ground (I made genericRewind.IsTracking = false; OnCollisionEnter).

I had to keep howManyRecordsPerSecond = Time.timeScale / Time.fixedDeltaTime; in CircularBuffer since I do not understand it and every change I tried weren't successfull.

I did not touch fixed timestep default values.

Also if I had to stick with FixedUpdate I would just have to disable gravity while rewinding but I still think it wouldn't be as smooth as what I saw with Update.

**Comment by SitronX** [comment]
You should not change Time.timeScale in runtime, this will cause some serious issues with Circular buffer values. It is also mentioned in [documentation](https://github.com/SitronX/UnityTimeRewinder/blob/main/Assets/TimeRewinder/Documentation/Unity%20Time%20Rewinder.pdf) on 6th page in <b>General mindset</b> section. Changing Time.timeScale is only possible before application is launched. 

Objects should not be falling by gravity when rewinding, because rewinds are connected with FixedUpdate() thus it is also connected with physics. There is no need to disable objects gravity when rewinding, objects should stay at same place, because their position is updated every physics frame essentialy disabling the gravity.

Are you using default rewind system inputs that are located [here](https://github.com/SitronX/UnityTimeRewinder/tree/main/Assets/TimeRewinder/TimeRewinderImplementation/Scripts/RewindInputs) or are you using your own input? If you are using your input, are you using it as is described in [documentation](https://github.com/SitronX/UnityTimeRewinder/blob/main/Assets/TimeRewinder/Documentation/Unity%20Time%20Rewinder.pdf) on 10th page in <b>Rewinding time thru code (Custom rewind inputs)</b>?  If you are using custom input, could you still please send here a snippet how are you using it?

**Comment by SitronX** [comment]
@Electorch  Hey is there any update on the matter? Did you manage to get it working?

**Comment by Electorch** [comment]
"the more times I rewind the more I'm missing until it just stop rewinding like it recorded only it's last position before hitting the ground" 
This does only happen in editor, application works correctly in a build.

**Comment by SitronX** [comment]
I am sorry man, but i cant really work magic here. 

You said you changed some code. I asked you to send here your code snippet. You are saying something is wrong, but how can i possibly help you if i dont even see the changes you made in the code. I need a way to reproduce it.

**Comment by Electorch** [comment]
I understand you believe I submitted an issue, yet it's simply "A way to make all this smoother".
There's nothing wrong and I did not ask for help.
Sorry, I don't need magic, your system works great.
